name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]
        test:
          [
            { name: "check", cmd: "check --all-features" },
            { name: "test", cmd: "test --all-features" },
            { name: "doc", cmd: "doc --all-features" },
            { name: "clippy", cmd: "clippy --all-features" },
            { name: "fmt", cmd: "fmt --check" },
          ]

    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.test.name }} ${{ matrix.lib }}
        run: cargo ${{ matrix.test.cmd }} --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml
