name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]

    steps:
      - uses: actions/checkout@v3
      - name: check ${{ matrix.lib }}
        run: cargo check --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]

    steps:
      - uses: actions/checkout@v3
      - name: test ${{ matrix.lib }}
        run: cargo test --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml

  clippy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]

    steps:
      - uses: actions/checkout@v3
      - name: clippy ${{ matrix.lib }}
        run: cargo clippy --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml
