name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]

    steps:
      - uses: actions/checkout@v3
      - name: build ${{ matrix.lib }}
        run: cargo build --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml
      - name: run test ${{ matrix.lib }}
        run: cargo test --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml
