name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "hmerr", "ux", "spof"]
        test: ["check", "test", "clippy"]

    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.test }} ${{ matrix.lib }}
        run: cargo ${{ matrix.test }} --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml
