name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lib: ["ansi", "ivec", "hmerr", "sna", "ux", "spof"]
        test:
          [
            { name: "check", arg: "--all-features" },
            { name: "test", arg: "--all-features" },
            { name: "doc", arg: "--all-features" },
            { name: "clippy", arg: "--all-features -- -D warnings" },
            { name: "fmt", arg: "--check" },
          ]

    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.test.name }} ${{ matrix.lib }}
        run: cargo ${{ matrix.test.name }} --verbose --manifest-path=lib/${{ matrix.lib }}/Cargo.toml ${{ matrix.test.arg }}
